###Author: Harry Fischl
###Processes coldCountTableRaw (from coldCountTableGeneration.R containing counts per PAS for each sample) to give:
###1) counts per Genes in RefSeq data base (counts from all PASs associated with each gene are summed)
###2) reads per million PAS-associated reads (RPM) normalized counts per PAS
###3) counts in reads per million per Genes in RefSeq data base (RPM-normalized counts from all PASs associated with each gene are summed)

###############################Work directories

TWD = getwd()
TWD1 = "./CountTables/"

###load raw count table generated by coldCountTableGeneration.R
load("./CountTables/coldCountTableRaw.Rda")

###file shows which PASs are associated with which RefSeq genes
load("./polyASites/reducedHumanPasToRefSeqGenes.Rda")
rpg = reducedHumanPasToRefSeqGenes

############Some PASs are associated with more than 1 gene - duplicate counts of these PASs into these genes
ctr = coldCountTableRaw
ctr1 = ctr[,c(7:length(ctr))]
row.names(ctr1) = ctr$pas
ctrn1 = ctr1[rpg$pas,]

###############################################

gepa = cbind(rpg,ctrn1)
coldPasForRefSeqGeneCountTable = gepa

setwd(TWD1)
#save(coldPasForRefSeqGeneCountTable, file="coldPasForRefSeqGeneCountTable.Rda")

###############################################
###############################################
#####Sum counts for all PASs associated with each gene to give gene counts table

agg1 = aggregate(ctrn1, by=list(rpg$gene), function(n) sum(n))
agg2 = as.matrix(agg1[,2:length(agg1)])
row.names(agg2) = agg1[,1]

coldRefSeqGeneCountTable = agg2
##############################################

setwd(TWD1)
#save(coldRefSeqGeneCountTable, file="coldRefSeqGeneCountTable.Rda")

#################################################################################
#################################################################################
####RPM normalization

ctr = coldCountTableRaw

ctr1 = ctr[,c(7:length(ctr))]
ctr2 = round(1000000*t(t(ctr1)/(colSums(ctr1))))

coldCountTableRPM = cbind(ctr[,c(1:6)],ctr2)

setwd(TWD1)
#save(coldCountTableRPM, file="coldCountTableRPM.Rda")

#############################################################################################
############Some PASs are associated with more than 1 gene - duplicate counts of these PASs into these genes
RPM = coldCountTableRPM
RPM1 = RPM[,c(7:length(RPM))]
row.names(RPM1) = ctr$pas
RPM2 = RPM1[rpg$pas,]

coldPasForRefSeqGeneRPMCountTable = cbind(rpg,RPM2)

setwd(TWD1)
#save(coldPasForRefSeqGeneRPMCountTable, file="coldPasForRefSeqGeneRPMCountTable.Rda")

###########################################################
#####Sum RPM-normalized counts for all PASs associated with each gene to give RPM gene counts table

agg1 = aggregate(RPM2, by=list(rpg$gene), function(n) sum(n))
agg2 = as.matrix(agg1[,2:length(agg1)])
row.names(agg2) = agg1[,1]

coldRefSeqGeneRPMCountTable = agg2
##############################################
setwd(TWD1)
#save(coldRefSeqGeneRPMCountTable, file="coldRefSeqGeneRPMCountTable.Rda")
